version: '3.3'

services:
  mongodb:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
      - ../Scrapper-data/data/normalized_stats_table.csv:/opt/data
    #      - docker-commands.sh:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lol_stats
      - MONGO_INITDB_ROOT_PASSWORD=lol_stats_pass